### ISSUE TITLE
License and Release/UseCase

### ISSUE THREAD

**Issue by Verser** [megamarc/Tilengine#4] opened 2016-08-02 23:18 UTC
Can anyone take TileEngine and wrap or alter the GUI and release it as part of modding or end user content creation? 

If someone wanted to take this code and make it as part of the game specific level editors, with hooks into the game database editor and animation editor? Think of RPGMaker style system where this would be the map element

I would like to release my first game on steam in the next year or so. It would be neat if I could release a set of tools that could work with steam workshop and general level editing.

**Comment by megamarc** [comment] 2016-08-03 14:13
Hi Verser, I don't quite understand your question. Tilengine hasn't a GUI and is not a content creation tool, is a graphics engine that must be interfaced from one of several programmimng languages (C, Java, Python, C#, Pascal...) to create an application.
That said, you cant use Tilengine in whatever project you have in mind. I would only ask for some acknowledgement in your "about" dialog or loading screen that it is powered by tilengine, so I can reference it in my web on "Made with tilengine" section.
Please let me know if you have more questions!

**Comment by megamarc** [comment] 2016-08-03 19:15
Yes, you're right, i mean you CAN use Tilengine without restrictions :) that was a typo...

**Comment by Verser** [comment] 2016-08-03 20:20
Oh Good! Ill see how far I can get it integrated, and let you know how it goes.

Thanks for this awesome lib!

**Comment by zatherz** [comment] 2017-01-12 21:30
You should choose an open source license such as MIT. A GitHub comment is not legally binding.

**Comment by Verser** [comment] 2017-01-12 21:37
I didn't think of that until now, good catch @zatherz . But yeah. Is there a chance you plan on doing that? We just started tasking out our tools set and will soon start working the TileEngine in.

Thoughts @megamarc

**Comment by megamarc** [comment] 2017-01-12 22:10
Hi guys, I'm doing a bit of research about licensing because I've been asked about it on other forums too. The concept is the MIT license: free for anything, without restrictions, no need to ask for it. But the MIT is an open-source license, and the Tilengine core is not. Some components are open-source (the loaders and built-in windowing) that use open-source licensed components (libpng and SDL) and some copyrighted but free module, but there are problems in releasing prebuilt binaries that cannot be built from source, although the source modules that use those components are open-sourced...

I've read that for closed-source software, one has to coin its own license. This licensing issue is getting quite tricky! :-(

**Comment by zatherz** [comment] 2017-01-12 22:32
"some copyrighted but free module" Which ones?

**Comment by megamarc** [comment] 2017-01-12 22:44
simplexml.c, to parse xml files

**Comment by megamarc** [comment] 2017-01-12 22:46
by international law, the author of any software is granted a copyright automatically without having to apply anywhere

**Comment by Verser** [comment] 2017-01-12 22:52
We're they made externally? As I am aware, if they were made for the OSS project they are part of it. Couldn't you request that part to be OSS as well, if that isnt the case.?

Also, grats on the coverage. Just in case you didn't know, [GameFromScratch is covering you!](http://www.gamefromscratch.com/post/2017/01/12/Hands-On-With-Tilengine.aspx) And he is great, all my game dev friends and myself read him.

**Comment by zatherz** [comment] 2017-01-12 23:29
Is this the right simplexml? https://sourceforge.net/projects/simplexml/

**Comment by zatherz** [comment] 2017-01-12 23:31
It's licensed under the BSD license, which is open source (similiar to MIT but has some patent protection, just for safety, if there are no other license issues, I'd license the whole engine as BSD)

**Comment by megamarc** [comment] 2017-01-14 08:10
Your comments about the licensing issue have been very helpful. The fact is that nor the MIT neither the BSD licenses require releasing the source code, whereas the GPL does. Hence the confusion. The Modified BSD (3 clauses) enforces author name protection (cannot be used on derived works without explicit permission), whereas the Simplified BSD License (2 clauses) and the MIT license are virtually equivalent.

As i'm not concerned about name endorsement, I think i'll put the 2-clauses BSD. And I think I should also reproduce the zlib license, to which libsdl2 and libpng adhere, isn't it?

**Comment by megamarc** [comment] 2017-01-14 14:54
Done. Released as FreeBSD license. Public sources updated with the license text at the top, and added the LICENSE.txt file.

**Comment by zatherz** [comment] 2017-01-14 19:54
Nice! I think this issue can be closed now.

**Closed** 2017-01-15 06:34 UTC
